<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GnsNet.Benchmarks</RootNamespace>
    <AssemblyName>GnsNet.Benchmarks</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/GnsNet/GnsNet.csproj" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>
</Project>
