namespace GnsNet.Generators;

using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

[Generator]
public sealed class NetSchemaGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("GNS001", "Generated schema requires partial type", "Type '{0}' must be partial when annotated with GenerateNetSchema", "GnsNet", DiagnosticSeverity.Error, true);
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ClassDeclarationSyntax> candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
            static (ctx, _) => (ClassDeclarationSyntax)ctx.Node).Where(static node => node.AttributeLists.Count > 0);
        context.RegisterSourceOutput(candidates, static (production, type) =>
        {
            string? attribute = type.AttributeLists.SelectMany(x => x.Attributes).Select(x => x.Name.ToString()).FirstOrDefault(x => x.EndsWith("GenerateNetSchema", StringComparison.Ordinal));
            if (attribute is null) return;
            if (!type.Modifiers.Any(x => x.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword))) { production.ReportDiagnostic(Diagnostic.Create(MustBePartial, type.Identifier.GetLocation(), type.Identifier.Text)); return; }
            string ns = GetNamespace(type); string name = type.Identifier.Text;
            string source = $"// <auto-generated />\nnamespace {ns};\npartial class {name}\n{{\n    public const int GeneratedNetworkSchemaVersion = 1;\n}}\n";
            production.AddSource($"{name}.GnsSchema.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
    private static string GetNamespace(ClassDeclarationSyntax type)
    {
        SyntaxNode? parent = type.Parent; while (parent is not null && parent is not BaseNamespaceDeclarationSyntax) parent = parent.Parent;
        return parent switch { BaseNamespaceDeclarationSyntax ns => ns.Name.ToString(), _ => "GnsNet.Generated" };
    }
}
