[CmdletBinding()]
param(
    [string]$OutputPath = "docs\api-reference.md",
    [string]$Configuration = "Release"
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$project = Join-Path $repo "src\GnsNet\GnsNet.csproj"
$xmlPath = Join-Path $repo "src\GnsNet\bin\$Configuration\net9.0\GnsNet.xml"
$output = [IO.Path]::GetFullPath((Join-Path $repo $OutputPath))

Push-Location $repo
try {
    & dotnet build $project --configuration $Configuration --no-restore -p:GnsNetBackend=Posix64
    if ($LASTEXITCODE -ne 0) { throw "API documentation build failed with exit code $LASTEXITCODE." }
} finally { Pop-Location }
if (-not (Test-Path -LiteralPath $xmlPath)) { throw "XML documentation was not generated: $xmlPath" }

[xml]$xml = Get-Content -LiteralPath $xmlPath -Raw
$lines = [Collections.Generic.List[string]]::new()
$lines.Add("# GNS.NET API reference")
$lines.Add("")
$lines.Add("Generated from the public XML documentation by `scripts/generate-api-reference.ps1`. Do not edit this file manually.")
$lines.Add("")
foreach ($member in $xml.doc.members.member | Sort-Object name) {
    $name = [string]$member.name
    if ($name -notmatch '^T:GnsNet\.' -and $name -notmatch '^M:GnsNet\.' -and $name -notmatch '^P:GnsNet\.' -and $name -notmatch '^E:GnsNet\.') { continue }
    $display = $name.Substring(2) -replace '#ctor$', 'constructor'
    $summary = ([string]$member.summary -replace '\s+', ' ').Trim()
    $lines.Add(('## `{0}`' -f $display))
    if ($summary) { $lines.Add(""); $lines.Add($summary) }
    $lines.Add("")
}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $output) | Out-Null
Set-Content -LiteralPath $output -Value ($lines -join [Environment]::NewLine) -Encoding utf8
Write-Host "Generated API reference: $output"
